---
# Playbook to install the Jekyll gem, and clone the blog's repo

- hosts: all
  remote_user: ubuntu

  tasks:

    - name: Install Python3 pip
      apt: name=python3-pip state=latest
      become: true

    - name: Install requests python library
      pip: name=requests state=latest executable=pip3
      become: true

    - name: Install Flask python library
      pip: name=flask state=latest executable=pip3
      become: true
    
    - name: Install Git
      apt: name=git state=latest
      become: true
    
    - name: Install Vim text editor
      apt: name=vim state=latest
      become: true 
