---
# Playbook to install the required tools and libraries for the Cisco DevNet Python tutorials

- hosts: all
  remote_user: ubuntu

  tasks:

    - name: Update apt cache if less than an hour old
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
    
    - name: Install Python3 pip
      apt: 
        name: python3-pip 
        state: latest 
      become: true

    - name: Install Python3 libxml
      apt:
        name: python3-lxml
        state: latest
      become: true

    - name: Install Python libxml2 development libraries
      apt:
        name: libxml2-dev
        state: latest
      become: true 

    - name: Install Python libxslt1
      apt:
        name: python-libxslt1
        state: latest
      become: true

    - name: Install libxslt1 development libraries
      apt:
        name: libxslt1-dev
        state: latest
      become: true

    - name: Install requests python library
      pip: 
        name: requests 
        state: latest 
        executable: pip3
      become: true

    - name: Install Flask python library
      pip: 
        name: flask 
        state: latest 
        executable: pip3
      become: true

    - name: Install netaddr
      pip:
        name: netaddr
        state: latest
        executable: pip3
      become: true

    - name: Install argparse
      pip:
        name: argparse
        state: latest
        executable: pip3
      become: true

    - name: Install Python YANG libraries
      pip:
        name: pyang
        state: latest
        executable: pip3
      become: true

    - name: Install Git
      apt: 
        name: git 
        state: latest
      become: true
    
    - name: Install Vim text editor
      apt: 
        name: vim 
        state: latest
      become: true 
